<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="BCTCW-DELL072" name="testcases.TC002_LoginFail" tests="1" failures="0" timestamp="08 Sep 2017 11:13:58 GMT" time="40.493" errors="1">
  <testcase name="login" time="40.493" classname="testcases.TC002_LoginFail">
    <error type="java.lang.RuntimeException" message="Failed">
      <![CDATA[java.lang.RuntimeException: Failed
	at utils.Reporter.reportStep(Reporter.java:39)
	at utils.Reporter.reportStep(Reporter.java:19)
	at pages.HomePage.<init>(HomePage.java:16)
	at pages.LoginPage.clickLogin(LoginPage.java:32)
	at testcases.TC002_LoginFail.login(TC002_LoginFail.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- login -->
</testsuite> <!-- testcases.TC002_LoginFail -->
